### ISSUE TITLE
Math notation does not work on exampleSite 

### ISSUE THREAD

**Issue by jpboignard** [chipzoller/hugo-clarity#24]
Hello,
I have installed the last version of hugo 0.74.3 extended, and setup a new site with the clarity theme as a git submodule then copy the given exampleSite at the root.
The "Math Typesetting" page does not display math notation.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: chrome and edge

Thanks

**Comment by onweru** [comment]
@jpboignard, thanks for raising this. I have attached screenshots of further diagnosis and [an explanation from the docs](https://gohugo.io/getting-started/configuration-markup/#goldmark) why this is happening. 

---
#### Diagnosis
 
<img width="892" alt="Screen Shot 2020-08-26 at 10 42 18 AM" src="https://user-images.githubusercontent.com/16350351/91318272-0ba32b00-e789-11ea-828d-83d61c6d54c8.png">

---
#### Docs

[See this section from the docs](https://gohugo.io/getting-started/configuration-markup/#goldmark)
<img width="630" alt="Screen Shot 2020-08-26 at 10 41 24 AM" src="https://user-images.githubusercontent.com/16350351/91318250-06de7700-e789-11ea-96b7-6d532abcaef0.png">

---
#### Solution

To remedy this, you can simply change [this line](https://github.com/chipzoller/hugo-clarity/blob/e696daf84770bc390ba773455faf294e3fc45055/exampleSite/config.toml#L24) in your `config.toml` to:

```
unsafe = true # change to false to disable inclusion of raw HTML and math functions
```

@chipzoller, I will need your help documenting this

**Comment by jpboignard** [comment]
It does not work for me.  
In the exampleSite, in safe or unsafe mode, the bottom of the page http://localhost:1313/post/math-typesetting/  only display this:
![image](https://user-images.githubusercontent.com/2809578/91351295-5acc7880-e7e8-11ea-9784-aa233cceafc0.png)

**Comment by onweru** [comment]
@jpboignard, if you don’t mind, I would like to see your code. Perhaps the config.toml & the math block you’re trying to publish

**Comment by onweru** [comment]
As it turns out, the answer to this issue is, in fact, [right under our nose](https://themes.gohugo.io//theme/hugo-clarity/post/math-typesetting/.). The first sentence of that posts states 👇 

> Mathematical notation in a Hugo project can __be enabled by using third party JavaScript libraries__.

In fact, the entire post documents how you activate math notation on a Hugo website.

When you look at the scripts loaded from the aforementioned link, you will notice `katex.min.js` is among them (see the attached screenshot). This means, [the Hugo themes site](https://themes.gohugo.io), a Hugo site, has implemented what is documented within the aforementioned post. 

Since this issue is already well documented (again, by the aforementioned post) I think we will document this only as an addendum.

No further changes will be required on this theme's config. 

@chipzoller, do you think we should treat this as a feature request? Maybe, go a little further and conditionally load the katex `third party JavaScript libraries` ? The condition would be as follows:

Sitewide via `config.toml` file

```yaml
...
[params]
...
enableMathNotation=false # change to true to activate math notation
...
```

It would be overridable from a page frontmatter

```yaml
...
[params]
...
enableMathNotation=true # I want to activate math notation on this page even if it's off site-wide
...
```

<img width="1132" alt="Screen Shot 2020-10-05 at 9 30 32 am" src="https://user-images.githubusercontent.com/16350351/95085634-7c752580-06ed-11eb-8668-1440119eb411.png">

**Comment by chipzoller** [comment]
I think this should be an enhancement, yes, and I also like the idea of activating it globally with per-page overrides like we have done with other parameters. Although our theme wasn't specifically designed to cater to math notation, it is somewhat of a relative of programming and other code. It seems like there should be similar facility to enable (and optimize for) its use.

**Comment by chipzoller** [comment]
@onweru I'm circling back on this as my task to update the README. Please confirm that the functionality is present and all that's needed from a docs standpoint is to write about the `enableMathNotation` in the `config.toml` file, overridable at the post level.
