### ISSUE TITLE
Figure Caption Double Up

### ISSUE THREAD

**Issue by rianbk** [chipzoller/hugo-clarity#265]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [Yes ] Read the README.md
- [Yes] Have the extended version of Hugo installed
- [Yes ] Used the exampleSite's config.toml as a reference
- [No(private)] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

Hi, I'm seem to be getting double figure captions after upgrading the theme (I was pretty far behind)
Example:
![image](https://user-images.githubusercontent.com/3753933/154793508-389f0bbd-573f-46f1-80af-a5f89d91f169.png)

from
![image](https://user-images.githubusercontent.com/3753933/154793540-9a99dc28-00ff-4fa6-aaf2-a1d1e751282e.png)

![image](https://user-images.githubusercontent.com/3753933/154793687-9d97b570-149c-4cf3-9c0b-cca69109b69b.png)

Live Post: https://rianbk.com/posts/2022-02-13-amazon-cloudfront-and-security-groups/

**Desktop (please complete the following information):**
OS: Win 11
Browser: Chrome

**Comment by rootwork** [comment]
I'm noticing this too. I wonder if I missed something in #206. I'm going to take a look.

**Comment by rootwork** [comment]
Oh, I think it was probably actually in the #219 follow-up.

**Comment by onweru** [comment]
Thanks @rianbk for reporting this issue. It has now been fixed.

@rootwork, you were almost caught it 😁. It was caused by the addition of [these lines](https://github.com/chipzoller/hugo-clarity/blob/17e6574dd5c9a87ab1033538a4b426ce9e93f18a/layouts/partials/image-feature.html#L67-L69). And the double captioning occurred only if you specified the image title in the markdown. 

Was quicker and solve it from the js script.

**Comment by chipzoller** [comment]
Awesome @onweru

**Comment by rootwork** [comment]
Thanks for finding it @onweru :)

**Comment by rianbk** [comment]
Hey all, thanks, can confirm this has resolved my issue.
