### ISSUE TITLE
All links opening in new tab

### ISSUE THREAD

**Issue by shawnmasters** [chipzoller/hugo-clarity#51]
My site has all clickable links (internal and external) opening in a new tab.  I'm fairly certain this has something to do with a URL setting like baseurl, but different options I have tried are not yielding any different results.  Here is the first few lines of my config.toml file.

```
# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "http://anticryptography.io/"  # Include trailing slash
title = "Anticryptography"
author = "Shawn Masters"
copyright = "Copyright © 2014–2020, Shawn Masters; all rights reserved."
canonifyurls = false
paginate = 10
theme = "hugo-clarity"

```

**Comment by onweru** [comment]
@shawnmasters,

Could you try 👇 

```
baseurl = "https://anticryptography.io/"
``` 

instead of

```
baseurl = "http://anticryptography.io/"
```

**Comment by onweru** [comment]
**Unrelated:** It might be a good idea to set a `http >> https` redirect on your server. If you're using netlify, [see the how to do it](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file) ... else look for a solution that fits your server. Why?

 1. because http://anticryptography.io/ is broken
2. because it's a good idea to always serve your site over `https`

**Comment by shawnmasters** [comment]
I did try both baseurl options with no difference.

HTTPS redirect is not available on the server I am currently using.  I had this working with both http and https problem using a much older (no longer available theme) before now.

**Comment by onweru** [comment]
@shawnmasters, let me know if it’s fixed now.

**Comment by shawnmasters** [comment]
That fixed it.  Thank you very much.
