### ISSUE TITLE
Adding double quotes to image caption text breaks rendering past that point.

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/hugo-clarity#73]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [ x] Read the README.md
- [x ] Have the extended version of Hugo installed
- [ x] Used the exampleSite's config.toml as a reference

**Describe the bug**
When an image caption text contains double quotes, the rendered output breaks at that point. Removing double quotes shows all the text as expected.

**Comment by onweru** [comment]
I looked into this. It turns out that this behavior is actually not a bug. It's a shortcoming of markdown itself. In markdown, if you include double quotes inside an image caption, markdown generates 'broken' html.

`![test "quotes" in markdown images](/images/thumbnail.png)` will produce the code in the attached screenshot. 
<img width="533" alt="Screen Shot 2020-11-04 at 9 41 02 am" src="https://user-images.githubusercontent.com/16350351/98125088-00a00180-1e82-11eb-8ee4-5d0eda4133c5.png">

You can always http://sparkandshine.net/en/insert-images-with-captions-in-markdown/

**Comment by chipzoller** [comment]
Thanks for investigating. Will convert to README guidance.

**Comment by chipzoller** [comment]
Closing via https://github.com/chipzoller/hugo-clarity/commit/90a2c009fb8b4dea9c5535f9aee88f8c905af055
