### ISSUE TITLE
Footer image location, override capabilities

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/hugo-clarity#77]
Footer image should be pulled or configurable from `/static/logos` and not in the theme directly. It's not clear where we're loading that footer image from.

**Comment by onweru** [comment]
I agree, currently we're using a favicon image for that.

**Comment by chipzoller** [comment]
Tabling for 2.0 milestone.

**Comment by onweru** [comment]
@chipzoller,

I think we need to add a section on the readme about overrides. I think adding a plethora of config fields to the `config.toml` is ultimately defeating. You can bet that dozens someones somewhere will want to override something that we never thought of.

Virtually all of these overrides can be achieved through a git traceable way. That is, without editing the theme itself. 

Basically, folks can override the behaviour of a template by duplicating it on their site's root. Then editing the duplicate as is  Hugo's way.

**Comment by chipzoller** [comment]
The footer image, though, is a central part of the branding and shouldn't come from within the theme itself. If it does, a user would never be able to reliably update Clarity without having to replace files.

**Comment by kozmotronik** [comment]
> The footer image, though, is a central part of the branding and shouldn't come from within the theme itself. If it does, a user would never be able to reliably update Clarity without having to replace files.

Now, 3 years later, as @chipzoller stated, it is crucial to be able to configure the site's footer logo without dip diving into the cloned theme folder.  

I am trying to change it but still haven't been able to since I am new to Hugo and am not a web developer.   

I copied the `footer.html` from the theme's partials to the site's layout/ partials directory and I'm trying to modify it with struggle.
